# Generated by Django 2.1.15 on 2023-07-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
