# Generated by Django 2.1.15 on 2023-07-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('documento', models.FloatField(null=True)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.FloatField(null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('servicio', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('fec_activacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'activaciones',
            },
        ),
    ]
