# Generated by Django 2.1.15 on 2023-07-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activacion',
            new_name='Activaciones',
        ),
    ]
