# Generated by Django 2.1.15 on 2023-07-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230723_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activaciones',
            name='documento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activaciones',
            name='fec_activacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activaciones',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
