# Generated by Django 2.1.15 on 2023-07-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230724_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('cliente', models.CharField(max_length=255)),
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(null=True)),
                ('plan', models.CharField(max_length=255)),
                ('ciclo_facturacion', models.IntegerField(null=True)),
                ('monto', models.FloatField(null=True)),
                ('fec_facturacion', models.DateField(null=True)),
            ],
            options={
                'db_table': 'facturacion',
            },
        ),
    ]
