# Generated by Django 2.1.15 on 2023-07-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='fec_facturacion',
            field=models.DateTimeField(null=True),
        ),
    ]
